//! One workbook, many sheets, each sheet its own table layout.
//!
//! `config.xlsx` (regenerated by `tools/gen-sheets`) holds:
//! - sheet `config` — `key,value[,format]` rows (`kv` — spreadsheets
//!   default to the `db` layout, so kv-shaped sheets say so)
//! - sheet `items`  — a record grid with a type row (`db`)
//! - sheet `npcs`   — a record grid without a type row: a `CustomLayout`
//!   inserts a row of `auto` cells and delegates back to `db`
//! - sheet `meta`   — column-oriented: a `CustomLayout` transposes it
//! - sheet `_extra` — `_`-prefixed (normally ignored), read here by
//!   naming it explicitly
//!
//! Every sheet-naming source merges under the sheet name as key, so the
//! sheets compose into one value without clobbering each other.
//!
//! Run inside this folder: `cd examples/xlsx-sheets && cargo run`
//! (expected output: `output.log` next to this file)

use c4::{CustomLayout, Format, Loader, Options, TableLayout};

#[derive(Debug, serde::Deserialize)]
#[allow(dead_code)] // fields are shown via Debug
struct Item {
    id: u32,
    name: String,
    price: f64,
}

fn main() -> Result<(), c4::Error> {
    // the db layout always expects a type row; for a grid without one,
    // insert a row of `auto` cells after the header and delegate back
    // to the db layout — every cell then auto-types
    let no_types = CustomLayout::new("db-no-types", |mut rows, path, options| {
        let width = rows.first().map(Vec::len).unwrap_or(0);
        rows.insert(1, vec!["auto".into(); width]);
        c4::parse_table(rows, &TableLayout::Db, path, options)
    });

    // another rows-level escape hatch: this sheet is column-oriented
    // (keys in row 1, values in row 2), so rotate it into kv rows and
    // reuse the standard table stage
    let transpose = CustomLayout::new("transpose", |rows, path, options| {
        let columns = rows.first().map(Vec::len).unwrap_or(0);
        let kv = (0..columns)
            .map(|i| rows.iter().filter_map(|row| row.get(i).cloned()).collect())
            .collect();
        c4::parse_table(kv, &TableLayout::Kv, path, options)
    });

    let loader = Loader::new(Options {
        sources: vec![
            // sheet sources are 4-tuples: sheet name + explicit layout
            (Format::Excel, "config.xlsx", "config", "kv").into(),
            (Format::Excel, "config.xlsx", "items", "db").into(),
            (Format::Excel, "config.xlsx", "npcs", no_types).into(),
            (Format::Excel, "config.xlsx", "meta", transpose).into(),
            (Format::Excel, "config.xlsx", "_extra", "kv").into(),
        ],
        ..Options::default()
    });

    // dynamic: the whole workbook as one value
    let value: c4::Value = loader.load()?;
    println!("title       = {:?}", value["config"]["title"].as_str());
    println!(
        "max_players = {:?}",
        value["config"]["max_players"].as_u64()
    );
    println!("author      = {:?}", value["meta"]["author"].as_str());
    println!("extra note  = {:?}", value["_extra"]["note"].as_str());

    // typed: a db-layout sheet is an array of records — a Vec of structs
    #[derive(serde::Deserialize)]
    struct Game {
        items: Vec<Item>,
    }
    let game: Game = loader.load()?;
    for item in &game.items {
        println!("item        = {item:?}");
    }
    Ok(())
}
